"""initial_migration

Revision ID: c1f54cdb5362
Revises: 
Create Date: 2024-06-09 20:09:39.943343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1f54cdb5362'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('postal', sa.String(), nullable=True),
    sa.Column('physical', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Deleted', 'Blocked', 'Pending', 'Used', name='entitystatus'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_created_at'), 'addresses', ['created_at'], unique=False)
    op.create_table('awards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('award_status', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('value_amount', sa.Float(), nullable=True),
    sa.Column('value_currency', sa.String(), nullable=True),
    sa.Column('ext_lot_number', sa.String(length=255), nullable=True),
    sa.Column('ext_tin', sa.String(length=255), nullable=True),
    sa.Column('ext_planning_reference_number', sa.String(length=255), nullable=True),
    sa.Column('ext_pe_code', sa.String(length=255), nullable=True),
    sa.Column('ext_tender_reference_number', sa.String(length=255), nullable=True),
    sa.Column('ext_fiscal_year', sa.String(length=255), nullable=True),
    sa.Column('ext_tender_type_code', sa.String(length=255), nullable=True),
    sa.Column('ext_tender_method_code', sa.String(length=255), nullable=True),
    sa.Column('ext_mod_date', sa.DateTime(), nullable=True),
    sa.Column('legacy_id', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Deleted', 'Blocked', 'Pending', 'Used', name='entitystatus'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_awards_created_at'), 'awards', ['created_at'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ocid', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contract_status', sa.String(), nullable=True),
    sa.Column('date_signed', sa.DateTime(), nullable=True),
    sa.Column('contract_period_start_date', sa.DateTime(), nullable=True),
    sa.Column('contract_period_end_date', sa.DateTime(), nullable=True),
    sa.Column('contract_period_max_extent_date', sa.DateTime(), nullable=True),
    sa.Column('contract_period_duration_in_days', sa.Integer(), nullable=True),
    sa.Column('value_amount', sa.Float(), nullable=True),
    sa.Column('value_currency', sa.String(), nullable=True),
    sa.Column('ext_tin', sa.String(length=255), nullable=True),
    sa.Column('ext_tender_reference_number', sa.String(length=255), nullable=True),
    sa.Column('ext_planning_reference_number', sa.String(length=255), nullable=True),
    sa.Column('ext_pe_code', sa.String(length=255), nullable=True),
    sa.Column('ext_fiscal_year', sa.String(length=255), nullable=True),
    sa.Column('ext_tender_type_code', sa.String(length=255), nullable=True),
    sa.Column('ext_tender_method_code', sa.String(length=255), nullable=True),
    sa.Column('ext_mod_date', sa.DateTime(), nullable=True),
    sa.Column('legacy_id', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Deleted', 'Blocked', 'Pending', 'Used', name='entitystatus'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_created_at'), 'contracts', ['created_at'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('date_published', sa.DateTime(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('ext_related_lot', sa.String(length=255), nullable=True),
    sa.Column('ext_mod_date', sa.DateTime(), nullable=True),
    sa.Column('reference_number', sa.String(length=255), nullable=True),
    sa.Column('reference_name', sa.String(length=255), nullable=True),
    sa.Column('reference_type', sa.Enum('PARTY', 'PLANNING', 'TENDER', 'AWARD', 'CONTRACT', 'IMPLEMENTATION', name='referencetype'), nullable=True),
    sa.Column('legacy_id', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Deleted', 'Blocked', 'Pending', 'Used', name='entitystatus'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_created_at'), 'document', ['created_at'], unique=False)
    op.create_table('item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('classification_scheme', sa.String(), nullable=True),
    sa.Column('classification_id', sa.String(), nullable=True),
    sa.Column('classification_description', sa.String(), nullable=True),
    sa.Column('classification_uri', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_name', sa.String(), nullable=True),
    sa.Column('unit_id', sa.String(), nullable=True),
    sa.Column('unit_scheme', sa.String(), nullable=True),
    sa.Column('unit_value_amount', sa.Float(), nullable=True),
    sa.Column('unit_value_currency', sa.String(), nullable=True),
    sa.Column('ext_mod_date', sa.DateTime(), nullable=True),
    sa.Column('reference_number', sa.String(length=255), nullable=True),
    sa.Column('reference_name', sa.String(length=255), nullable=True),
    sa.Column('reference_type', sa.Enum('PARTY', 'PLANNING', 'TENDER', 'AWARD', 'CONTRACT', 'IMPLEMENTATION', name='referencetype'), nullable=True),
    sa.Column('legacy_id', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Deleted', 'Blocked', 'Pending', 'Used', name='entitystatus'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_created_at'), 'item', ['created_at'], unique=False)
    op.create_table('lot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Deleted', 'Blocked', 'Pending', 'Used', name='entitystatus'), nullable=True),
    sa.Column('value_amount', sa.Float(), nullable=True),
    sa.Column('value_currency', sa.String(), nullable=True),
    sa.Column('contract_period_start_date', sa.DateTime(), nullable=True),
    sa.Column('contract_period_end_date', sa.DateTime(), nullable=True),
    sa.Column('contract_period_duration_in_days', sa.Integer(), nullable=True),
    sa.Column('ext_mod_date', sa.DateTime(), nullable=True),
    sa.Column('legacy_id', sa.String(length=255), nullable=True),
    sa.Column('reference_number', sa.String(length=255), nullable=True),
    sa.Column('reference_name', sa.String(length=255), nullable=True),
    sa.Column('reference_type', sa.Enum('PARTY', 'PLANNING', 'TENDER', 'AWARD', 'CONTRACT', 'IMPLEMENTATION', name='referencetype'), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lot_created_at'), 'lot', ['created_at'], unique=False)
    op.create_table('milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('milestone_status', sa.String(length=50), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('date_met', sa.DateTime(), nullable=True),
    sa.Column('reference_number', sa.String(length=255), nullable=True),
    sa.Column('reference_name', sa.String(length=255), nullable=True),
    sa.Column('reference_type', sa.Enum('PARTY', 'PLANNING', 'TENDER', 'AWARD', 'CONTRACT', 'IMPLEMENTATION', name='referencetype'), nullable=True),
    sa.Column('legacy_id', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Deleted', 'Blocked', 'Pending', 'Used', name='entitystatus'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestones_created_at'), 'milestones', ['created_at'], unique=False)
    op.create_table('party',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('roles', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('identifier_scheme', sa.String(length=50), nullable=True),
    sa.Column('identifier_id', sa.String(length=50), nullable=True),
    sa.Column('identifier_legal_name', sa.String(length=255), nullable=True),
    sa.Column('address_street', sa.Text(), nullable=True),
    sa.Column('address_locality', sa.Text(), nullable=True),
    sa.Column('address_region', sa.Text(), nullable=True),
    sa.Column('address_postal_code', sa.Text(), nullable=True),
    sa.Column('address_country_name', sa.Text(), nullable=True),
    sa.Column('contact_point_name', sa.String(length=250), nullable=True),
    sa.Column('contact_point_email', sa.String(length=250), nullable=True),
    sa.Column('contact_point_telephone', sa.String(length=250), nullable=True),
    sa.Column('contact_point_fax_number', sa.String(length=250), nullable=True),
    sa.Column('contact_point_url', sa.String(length=250), nullable=True),
    sa.Column('ext_tin', sa.String(length=255), nullable=True),
    sa.Column('ext_mod_date', sa.DateTime(), nullable=True),
    sa.Column('legacy_id', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Deleted', 'Blocked', 'Pending', 'Used', name='entitystatus'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_party_created_at'), 'party', ['created_at'], unique=False)
    op.create_table('planning',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('ocid', sa.String(length=255), nullable=True),
    sa.Column('budget_id', sa.String(length=255), nullable=True),
    sa.Column('budget_description', sa.Text(), nullable=True),
    sa.Column('budget_project', sa.String(length=255), nullable=True),
    sa.Column('budget_project_id', sa.String(length=50), nullable=True),
    sa.Column('budget_amount', sa.Numeric(precision=35, scale=2), nullable=True),
    sa.Column('budget_currency', sa.String(length=3), nullable=True),
    sa.Column('budget_uri', sa.String(length=255), nullable=True),
    sa.Column('ext_pe_code', sa.String(length=255), nullable=True),
    sa.Column('ext_fiscal_year', sa.String(length=255), nullable=True),
    sa.Column('ext_tender_type_code', sa.String(length=255), nullable=True),
    sa.Column('ext_tender_method_code', sa.String(length=255), nullable=True),
    sa.Column('ext_mod_date', sa.DateTime(), nullable=True),
    sa.Column('ext_revw_serno', sa.String(length=255), nullable=True),
    sa.Column('legacy_id', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Deleted', 'Blocked', 'Pending', 'Used', name='entitystatus'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planning_created_at'), 'planning', ['created_at'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Deleted', 'Blocked', 'Pending', 'Used', name='entitystatus'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_created_at'), 'tenants', ['created_at'], unique=False)
    op.create_table('tender',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('main_procurement_category', sa.String(), nullable=True),
    sa.Column('tender_status', sa.String(), nullable=True),
    sa.Column('min_value_amount', sa.Float(), nullable=True),
    sa.Column('min_value_currency', sa.String(), nullable=True),
    sa.Column('value_amount', sa.Float(), nullable=True),
    sa.Column('value_currency', sa.String(length=256), nullable=True),
    sa.Column('procurement_method', sa.String(), nullable=True),
    sa.Column('procurement_method_details', sa.String(), nullable=True),
    sa.Column('procurement_method_rationale', sa.String(), nullable=True),
    sa.Column('award_criteria', sa.String(), nullable=True),
    sa.Column('award_criteria_details', sa.String(), nullable=True),
    sa.Column('submission_method', sa.String(), nullable=True),
    sa.Column('submission_method_details', sa.String(), nullable=True),
    sa.Column('has_enquiries', sa.Boolean(), nullable=True),
    sa.Column('tender_period_start_date', sa.DateTime(), nullable=True),
    sa.Column('tender_period_end_date', sa.DateTime(), nullable=True),
    sa.Column('tender_period_duration_in_days', sa.Integer(), nullable=True),
    sa.Column('enquiry_period_start_date', sa.DateTime(), nullable=True),
    sa.Column('enquiry_period_end_date', sa.DateTime(), nullable=True),
    sa.Column('enquiry_period_duration_in_days', sa.Integer(), nullable=True),
    sa.Column('award_period_start_date', sa.DateTime(), nullable=True),
    sa.Column('award_period_end_date', sa.DateTime(), nullable=True),
    sa.Column('contract_period_start_date', sa.DateTime(), nullable=True),
    sa.Column('contract_period_end_date', sa.DateTime(), nullable=True),
    sa.Column('contract_period_duration_in_days', sa.Integer(), nullable=True),
    sa.Column('participation_fees_id', sa.String(length=255), nullable=True),
    sa.Column('participation_fees_value_amount', sa.Text(), nullable=True),
    sa.Column('participation_fees_value_currency', sa.Text(), nullable=True),
    sa.Column('ext_tender_estimated_value', sa.Float(), nullable=True),
    sa.Column('ext_tender_estimated_currency', sa.String(), nullable=True),
    sa.Column('ext_planning_reference_number', sa.String(length=255), nullable=True),
    sa.Column('ext_pe_code', sa.String(length=255), nullable=True),
    sa.Column('ext_fiscal_year', sa.String(length=255), nullable=True),
    sa.Column('ext_tender_type_code', sa.String(length=255), nullable=True),
    sa.Column('ext_tender_method_code', sa.String(length=255), nullable=True),
    sa.Column('ext_mod_date', sa.DateTime(), nullable=True),
    sa.Column('ext_rgt_type_code', sa.String(length=255), nullable=True),
    sa.Column('ext_tender_stage_code', sa.String(length=255), nullable=True),
    sa.Column('legacy_id', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Deleted', 'Blocked', 'Pending', 'Used', name='entitystatus'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_created_at'), 'tender', ['created_at'], unique=False)
    op.create_table('tenant_addresses',
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('address_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], )
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Deleted', 'Blocked', 'Pending', 'Used', name='entitystatus'), nullable=True),
    sa.Column('role_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('salt', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Deleted', 'Blocked', 'Pending', 'Used', name='entitystatus'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_created_at'), 'credentials', ['created_at'], unique=False)
    op.create_table('otp',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Deleted', 'Blocked', 'Pending', 'Used', name='entitystatus'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_created_at'), 'otp', ['created_at'], unique=False)
    op.create_table('tenant_users',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('user_addresses',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('address_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_addresses')
    op.drop_table('tenant_users')
    op.drop_index(op.f('ix_otp_created_at'), table_name='otp')
    op.drop_table('otp')
    op.drop_index(op.f('ix_credentials_created_at'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_table('tenant_addresses')
    op.drop_index(op.f('ix_tender_created_at'), table_name='tender')
    op.drop_table('tender')
    op.drop_index(op.f('ix_tenants_created_at'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_table('roles')
    op.drop_index(op.f('ix_planning_created_at'), table_name='planning')
    op.drop_table('planning')
    op.drop_index(op.f('ix_party_created_at'), table_name='party')
    op.drop_table('party')
    op.drop_index(op.f('ix_milestones_created_at'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_lot_created_at'), table_name='lot')
    op.drop_table('lot')
    op.drop_index(op.f('ix_item_created_at'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_document_created_at'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_contracts_created_at'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_awards_created_at'), table_name='awards')
    op.drop_table('awards')
    op.drop_index(op.f('ix_addresses_created_at'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
