"""Update thread and message schema to include users information

Revision ID: 4db18e888071
Revises: 79eacefb83cd
Create Date: 2024-06-20 15:07:59.307266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4db18e888071'
down_revision: Union[str, None] = '79eacefb83cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('role', sa.String(), nullable=True))
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'])
    op.drop_column('messages', 'sender')
    op.add_column('threads', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('threads', sa.Column('title', sa.String(), nullable=True))
    op.create_foreign_key(None, 'threads', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'threads', type_='foreignkey')
    op.drop_column('threads', 'title')
    op.drop_column('threads', 'user_id')
    op.add_column('messages', sa.Column('sender', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'role')
    op.drop_column('messages', 'user_id')
    # ### end Alembic commands ###
