"""Update database to add workspace model

Revision ID: 56cb7a903bfd
Revises: 23c2a90ad618
Create Date: 2024-07-24 19:29:37.797998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56cb7a903bfd'
down_revision: Union[str, None] = '23c2a90ad618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_created_at'), 'workspaces', ['created_at'], unique=False)
    op.create_table('workspace_users',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], )
    )
    op.add_column('threads', sa.Column('workspace_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'threads', 'workspaces', ['workspace_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'threads', type_='foreignkey')
    op.drop_column('threads', 'workspace_id')
    op.drop_table('workspace_users')
    op.drop_index(op.f('ix_workspaces_created_at'), table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
