"""Added backprops for user's role and remove backref on role

Revision ID: 82e7160f4a2e
Revises: c3868b81915a
Create Date: 2024-08-26 06:10:12.194873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e7160f4a2e'
down_revision: Union[str, None] = 'c3868b81915a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
