"""Update message schema

Revision ID: a3b4a915521d
Revises: e66c0df2104a
Create Date: 2024-06-21 04:43:50.039682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3b4a915521d'
down_revision: Union[str, None] = 'e66c0df2104a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('annotations', sa.ARRAY(sa.JSON()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'annotations')
    # ### end Alembic commands ###
