"""Added backprops for user's role and remove backref on role

Revision ID: c3868b81915a
Revises: e4f9b8aaf148
Create Date: 2024-08-26 06:06:34.042385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3868b81915a'
down_revision: Union[str, None] = 'e4f9b8aaf148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
