"""Added backprops for user's role

Revision ID: e4f9b8aaf148
Revises: 3ac1f3263e3a
Create Date: 2024-08-26 05:47:50.256077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4f9b8aaf148'
down_revision: Union[str, None] = '3ac1f3263e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
